common:
  use_cuda: !!bool True
  checkpoint_folder: './log/hai_ba/checkpoint' # Folder contains checkpoit
  sample_folder: './log/hai_ba/sample' # Folder contains sample in training process

data:
  first_user: './data/cropped_faces_hai' # Folder contains images of first user
  second_user: './data/cropped_faces_hai_ba' # Folder contains images of second user

train:
  learning_rate: 0.005
  batch_size: 16
  epochs: 20000
  sample_number: 5
  continue_once: !!bool False
  seed: 1234

model:
  image_size: 256
  in_channels: 3
  latent_dim: 256
  kld_weight: 0.00025

test:
  checkpoint_path: ./checkpoint/ba/checkpoint_2187.pt # Path to checkpoint used for inference process
